package com.example.healthapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AdministrareAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdministrareAllPropertiesEquals(Administrare expected, Administrare actual) {
        assertAdministrareAutoGeneratedPropertiesEquals(expected, actual);
        assertAdministrareAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdministrareAllUpdatablePropertiesEquals(Administrare expected, Administrare actual) {
        assertAdministrareUpdatableFieldsEquals(expected, actual);
        assertAdministrareUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdministrareAutoGeneratedPropertiesEquals(Administrare expected, Administrare actual) {
        assertThat(actual)
            .as("Verify Administrare auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdministrareUpdatableFieldsEquals(Administrare expected, Administrare actual) {
        assertThat(actual)
            .as("Verify Administrare relevant properties")
            .satisfies(a -> assertThat(a.getDataAdministrare()).as("check dataAdministrare").isEqualTo(expected.getDataAdministrare()))
            .satisfies(a -> assertThat(a.getTipTratament()).as("check tipTratament").isEqualTo(expected.getTipTratament()))
            .satisfies(a -> assertThat(a.getDoza()).as("check doza").isEqualTo(expected.getDoza()))
            .satisfies(a -> assertThat(a.getUnitate()).as("check unitate").isEqualTo(expected.getUnitate()))
            .satisfies(a -> assertThat(a.getModAdministrare()).as("check modAdministrare").isEqualTo(expected.getModAdministrare()))
            .satisfies(a -> assertThat(a.getObservatii()).as("check observatii").isEqualTo(expected.getObservatii()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdministrareUpdatableRelationshipsEquals(Administrare expected, Administrare actual) {
        assertThat(actual)
            .as("Verify Administrare relationships")
            .satisfies(a -> assertThat(a.getPacient()).as("check pacient").isEqualTo(expected.getPacient()))
            .satisfies(a -> assertThat(a.getFarmacist()).as("check farmacist").isEqualTo(expected.getFarmacist()));
    }
}
