package com.example.healthapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AlocareTratamentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlocareTratamentAllPropertiesEquals(AlocareTratament expected, AlocareTratament actual) {
        assertAlocareTratamentAutoGeneratedPropertiesEquals(expected, actual);
        assertAlocareTratamentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlocareTratamentAllUpdatablePropertiesEquals(AlocareTratament expected, AlocareTratament actual) {
        assertAlocareTratamentUpdatableFieldsEquals(expected, actual);
        assertAlocareTratamentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlocareTratamentAutoGeneratedPropertiesEquals(AlocareTratament expected, AlocareTratament actual) {
        assertThat(actual)
            .as("Verify AlocareTratament auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlocareTratamentUpdatableFieldsEquals(AlocareTratament expected, AlocareTratament actual) {
        assertThat(actual)
            .as("Verify AlocareTratament relevant properties")
            .satisfies(a -> assertThat(a.getDataDecizie()).as("check dataDecizie").isEqualTo(expected.getDataDecizie()))
            .satisfies(a -> assertThat(a.getTratamentPropus()).as("check tratamentPropus").isEqualTo(expected.getTratamentPropus()))
            .satisfies(a -> assertThat(a.getMotivDecizie()).as("check motivDecizie").isEqualTo(expected.getMotivDecizie()))
            .satisfies(a -> assertThat(a.getScorDecizie()).as("check scorDecizie").isEqualTo(expected.getScorDecizie()))
            .satisfies(a -> assertThat(a.getDecizieValidata()).as("check decizieValidata").isEqualTo(expected.getDecizieValidata()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlocareTratamentUpdatableRelationshipsEquals(AlocareTratament expected, AlocareTratament actual) {
        assertThat(actual)
            .as("Verify AlocareTratament relationships")
            .satisfies(a -> assertThat(a.getMedic()).as("check medic").isEqualTo(expected.getMedic()))
            .satisfies(a -> assertThat(a.getMedicament()).as("check medicament").isEqualTo(expected.getMedicament()))
            .satisfies(a -> assertThat(a.getPacient()).as("check pacient").isEqualTo(expected.getPacient()));
    }
}
