package com.example.healthapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DecisionLogAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDecisionLogAllPropertiesEquals(DecisionLog expected, DecisionLog actual) {
        assertDecisionLogAutoGeneratedPropertiesEquals(expected, actual);
        assertDecisionLogAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDecisionLogAllUpdatablePropertiesEquals(DecisionLog expected, DecisionLog actual) {
        assertDecisionLogUpdatableFieldsEquals(expected, actual);
        assertDecisionLogUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDecisionLogAutoGeneratedPropertiesEquals(DecisionLog expected, DecisionLog actual) {
        assertThat(actual)
            .as("Verify DecisionLog auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDecisionLogUpdatableFieldsEquals(DecisionLog expected, DecisionLog actual) {
        assertThat(actual)
            .as("Verify DecisionLog relevant properties")
            .satisfies(a -> assertThat(a.getTimestamp()).as("check timestamp").isEqualTo(expected.getTimestamp()))
            .satisfies(a -> assertThat(a.getActorType()).as("check actorType").isEqualTo(expected.getActorType()))
            .satisfies(a -> assertThat(a.getRecomandare()).as("check recomandare").isEqualTo(expected.getRecomandare()))
            .satisfies(a -> assertThat(a.getModelScore()).as("check modelScore").isEqualTo(expected.getModelScore()))
            .satisfies(a -> assertThat(a.getReguliTriggered()).as("check reguliTriggered").isEqualTo(expected.getReguliTriggered()))
            .satisfies(a -> assertThat(a.getExternalChecks()).as("check externalChecks").isEqualTo(expected.getExternalChecks()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDecisionLogUpdatableRelationshipsEquals(DecisionLog expected, DecisionLog actual) {
        assertThat(actual)
            .as("Verify DecisionLog relationships")
            .satisfies(a -> assertThat(a.getAlocare()).as("check alocare").isEqualTo(expected.getAlocare()));
    }
}
