package com.example.healthapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ExternalDrugInfoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExternalDrugInfoAllPropertiesEquals(ExternalDrugInfo expected, ExternalDrugInfo actual) {
        assertExternalDrugInfoAutoGeneratedPropertiesEquals(expected, actual);
        assertExternalDrugInfoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExternalDrugInfoAllUpdatablePropertiesEquals(ExternalDrugInfo expected, ExternalDrugInfo actual) {
        assertExternalDrugInfoUpdatableFieldsEquals(expected, actual);
        assertExternalDrugInfoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExternalDrugInfoAutoGeneratedPropertiesEquals(ExternalDrugInfo expected, ExternalDrugInfo actual) {
        assertThat(actual)
            .as("Verify ExternalDrugInfo auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExternalDrugInfoUpdatableFieldsEquals(ExternalDrugInfo expected, ExternalDrugInfo actual) {
        assertThat(actual)
            .as("Verify ExternalDrugInfo relevant properties")
            .satisfies(a -> assertThat(a.getSource()).as("check source").isEqualTo(expected.getSource()))
            .satisfies(a -> assertThat(a.getProductSummary()).as("check productSummary").isEqualTo(expected.getProductSummary()))
            .satisfies(a -> assertThat(a.getLastUpdated()).as("check lastUpdated").isEqualTo(expected.getLastUpdated()))
            .satisfies(a -> assertThat(a.getSourceUrl()).as("check sourceUrl").isEqualTo(expected.getSourceUrl()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExternalDrugInfoUpdatableRelationshipsEquals(ExternalDrugInfo expected, ExternalDrugInfo actual) {
        // empty method
    }
}
