package com.example.healthapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FarmacistAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFarmacistAllPropertiesEquals(Farmacist expected, Farmacist actual) {
        assertFarmacistAutoGeneratedPropertiesEquals(expected, actual);
        assertFarmacistAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFarmacistAllUpdatablePropertiesEquals(Farmacist expected, Farmacist actual) {
        assertFarmacistUpdatableFieldsEquals(expected, actual);
        assertFarmacistUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFarmacistAutoGeneratedPropertiesEquals(Farmacist expected, Farmacist actual) {
        assertThat(actual)
            .as("Verify Farmacist auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFarmacistUpdatableFieldsEquals(Farmacist expected, Farmacist actual) {
        assertThat(actual)
            .as("Verify Farmacist relevant properties")
            .satisfies(a -> assertThat(a.getNume()).as("check nume").isEqualTo(expected.getNume()))
            .satisfies(a -> assertThat(a.getPrenume()).as("check prenume").isEqualTo(expected.getPrenume()))
            .satisfies(a -> assertThat(a.getFarmacie()).as("check farmacie").isEqualTo(expected.getFarmacie()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getTelefon()).as("check telefon").isEqualTo(expected.getTelefon()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFarmacistUpdatableRelationshipsEquals(Farmacist expected, Farmacist actual) {
        // empty method
    }
}
