package com.example.healthapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MedicamentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicamentAllPropertiesEquals(Medicament expected, Medicament actual) {
        assertMedicamentAutoGeneratedPropertiesEquals(expected, actual);
        assertMedicamentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicamentAllUpdatablePropertiesEquals(Medicament expected, Medicament actual) {
        assertMedicamentUpdatableFieldsEquals(expected, actual);
        assertMedicamentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicamentAutoGeneratedPropertiesEquals(Medicament expected, Medicament actual) {
        assertThat(actual)
            .as("Verify Medicament auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicamentUpdatableFieldsEquals(Medicament expected, Medicament actual) {
        assertThat(actual)
            .as("Verify Medicament relevant properties")
            .satisfies(a -> assertThat(a.getDenumire()).as("check denumire").isEqualTo(expected.getDenumire()))
            .satisfies(a -> assertThat(a.getSubstanta()).as("check substanta").isEqualTo(expected.getSubstanta()))
            .satisfies(a -> assertThat(a.getIndicatii()).as("check indicatii").isEqualTo(expected.getIndicatii()))
            .satisfies(a -> assertThat(a.getContraindicatii()).as("check contraindicatii").isEqualTo(expected.getContraindicatii()))
            .satisfies(a -> assertThat(a.getInteractiuni()).as("check interactiuni").isEqualTo(expected.getInteractiuni()))
            .satisfies(a -> assertThat(a.getDozaRecomandata()).as("check dozaRecomandata").isEqualTo(expected.getDozaRecomandata()))
            .satisfies(a -> assertThat(a.getFormaFarmaceutica()).as("check formaFarmaceutica").isEqualTo(expected.getFormaFarmaceutica()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicamentUpdatableRelationshipsEquals(Medicament expected, Medicament actual) {
        assertThat(actual)
            .as("Verify Medicament relationships")
            .satisfies(a -> assertThat(a.getInfoExtern()).as("check infoExtern").isEqualTo(expected.getInfoExtern()));
    }
}
