package com.example.healthapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MonitorizareAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMonitorizareAllPropertiesEquals(Monitorizare expected, Monitorizare actual) {
        assertMonitorizareAutoGeneratedPropertiesEquals(expected, actual);
        assertMonitorizareAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMonitorizareAllUpdatablePropertiesEquals(Monitorizare expected, Monitorizare actual) {
        assertMonitorizareUpdatableFieldsEquals(expected, actual);
        assertMonitorizareUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMonitorizareAutoGeneratedPropertiesEquals(Monitorizare expected, Monitorizare actual) {
        assertThat(actual)
            .as("Verify Monitorizare auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMonitorizareUpdatableFieldsEquals(Monitorizare expected, Monitorizare actual) {
        assertThat(actual)
            .as("Verify Monitorizare relevant properties")
            .satisfies(a -> assertThat(a.getDataInstant()).as("check dataInstant").isEqualTo(expected.getDataInstant()))
            .satisfies(a -> assertThat(a.getTensiuneSist()).as("check tensiuneSist").isEqualTo(expected.getTensiuneSist()))
            .satisfies(a -> assertThat(a.getTensiuneDiast()).as("check tensiuneDiast").isEqualTo(expected.getTensiuneDiast()))
            .satisfies(a -> assertThat(a.getPuls()).as("check puls").isEqualTo(expected.getPuls()))
            .satisfies(a -> assertThat(a.getGlicemie()).as("check glicemie").isEqualTo(expected.getGlicemie()))
            .satisfies(a -> assertThat(a.getScorEficacitate()).as("check scorEficacitate").isEqualTo(expected.getScorEficacitate()))
            .satisfies(a -> assertThat(a.getComentarii()).as("check comentarii").isEqualTo(expected.getComentarii()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMonitorizareUpdatableRelationshipsEquals(Monitorizare expected, Monitorizare actual) {
        assertThat(actual)
            .as("Verify Monitorizare relationships")
            .satisfies(a -> assertThat(a.getPacient()).as("check pacient").isEqualTo(expected.getPacient()));
    }
}
