package com.example.healthapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PacientAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPacientAllPropertiesEquals(Pacient expected, Pacient actual) {
        assertPacientAutoGeneratedPropertiesEquals(expected, actual);
        assertPacientAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPacientAllUpdatablePropertiesEquals(Pacient expected, Pacient actual) {
        assertPacientUpdatableFieldsEquals(expected, actual);
        assertPacientUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPacientAutoGeneratedPropertiesEquals(Pacient expected, Pacient actual) {
        assertThat(actual)
            .as("Verify Pacient auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPacientUpdatableFieldsEquals(Pacient expected, Pacient actual) {
        assertThat(actual)
            .as("Verify Pacient relevant properties")
            .satisfies(a -> assertThat(a.getNume()).as("check nume").isEqualTo(expected.getNume()))
            .satisfies(a -> assertThat(a.getPrenume()).as("check prenume").isEqualTo(expected.getPrenume()))
            .satisfies(a -> assertThat(a.getSex()).as("check sex").isEqualTo(expected.getSex()))
            .satisfies(a -> assertThat(a.getVarsta()).as("check varsta").isEqualTo(expected.getVarsta()))
            .satisfies(a -> assertThat(a.getGreutate()).as("check greutate").isEqualTo(expected.getGreutate()))
            .satisfies(a -> assertThat(a.getInaltime()).as("check inaltime").isEqualTo(expected.getInaltime()))
            .satisfies(a ->
                assertThat(a.getCircumferintaAbdominala())
                    .as("check circumferintaAbdominala")
                    .isEqualTo(expected.getCircumferintaAbdominala())
            )
            .satisfies(a -> assertThat(a.getCnp()).as("check cnp").isEqualTo(expected.getCnp()))
            .satisfies(a -> assertThat(a.getComorbiditati()).as("check comorbiditati").isEqualTo(expected.getComorbiditati()))
            .satisfies(a -> assertThat(a.getGradSedentarism()).as("check gradSedentarism").isEqualTo(expected.getGradSedentarism()))
            .satisfies(a -> assertThat(a.getIstoricTratament()).as("check istoricTratament").isEqualTo(expected.getIstoricTratament()))
            .satisfies(a -> assertThat(a.getToleranta()).as("check toleranta").isEqualTo(expected.getToleranta()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getTelefon()).as("check telefon").isEqualTo(expected.getTelefon()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPacientUpdatableRelationshipsEquals(Pacient expected, Pacient actual) {
        assertThat(actual)
            .as("Verify Pacient relationships")
            .satisfies(a -> assertThat(a.getMedic()).as("check medic").isEqualTo(expected.getMedic()))
            .satisfies(a -> assertThat(a.getFarmacist()).as("check farmacist").isEqualTo(expected.getFarmacist()));
    }
}
