package com.example.healthapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RaportAnaliticAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRaportAnaliticAllPropertiesEquals(RaportAnalitic expected, RaportAnalitic actual) {
        assertRaportAnaliticAutoGeneratedPropertiesEquals(expected, actual);
        assertRaportAnaliticAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRaportAnaliticAllUpdatablePropertiesEquals(RaportAnalitic expected, RaportAnalitic actual) {
        assertRaportAnaliticUpdatableFieldsEquals(expected, actual);
        assertRaportAnaliticUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRaportAnaliticAutoGeneratedPropertiesEquals(RaportAnalitic expected, RaportAnalitic actual) {
        assertThat(actual)
            .as("Verify RaportAnalitic auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRaportAnaliticUpdatableFieldsEquals(RaportAnalitic expected, RaportAnalitic actual) {
        assertThat(actual)
            .as("Verify RaportAnalitic relevant properties")
            .satisfies(a -> assertThat(a.getPerioadaStart()).as("check perioadaStart").isEqualTo(expected.getPerioadaStart()))
            .satisfies(a -> assertThat(a.getPerioadaEnd()).as("check perioadaEnd").isEqualTo(expected.getPerioadaEnd()))
            .satisfies(a -> assertThat(a.getEficientaMedie()).as("check eficientaMedie").isEqualTo(expected.getEficientaMedie()))
            .satisfies(a -> assertThat(a.getRataReactiiAdverse()).as("check rataReactiiAdverse").isEqualTo(expected.getRataReactiiAdverse())
            )
            .satisfies(a -> assertThat(a.getObservatii()).as("check observatii").isEqualTo(expected.getObservatii()))
            .satisfies(a -> assertThat(a.getConcluzii()).as("check concluzii").isEqualTo(expected.getConcluzii()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRaportAnaliticUpdatableRelationshipsEquals(RaportAnalitic expected, RaportAnalitic actual) {
        assertThat(actual)
            .as("Verify RaportAnalitic relationships")
            .satisfies(a -> assertThat(a.getMedicament()).as("check medicament").isEqualTo(expected.getMedicament()))
            .satisfies(a -> assertThat(a.getMedic()).as("check medic").isEqualTo(expected.getMedic()));
    }
}
