package com.example.healthapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ReactieAdversaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReactieAdversaAllPropertiesEquals(ReactieAdversa expected, ReactieAdversa actual) {
        assertReactieAdversaAutoGeneratedPropertiesEquals(expected, actual);
        assertReactieAdversaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReactieAdversaAllUpdatablePropertiesEquals(ReactieAdversa expected, ReactieAdversa actual) {
        assertReactieAdversaUpdatableFieldsEquals(expected, actual);
        assertReactieAdversaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReactieAdversaAutoGeneratedPropertiesEquals(ReactieAdversa expected, ReactieAdversa actual) {
        assertThat(actual)
            .as("Verify ReactieAdversa auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReactieAdversaUpdatableFieldsEquals(ReactieAdversa expected, ReactieAdversa actual) {
        assertThat(actual)
            .as("Verify ReactieAdversa relevant properties")
            .satisfies(a -> assertThat(a.getDataRaportare()).as("check dataRaportare").isEqualTo(expected.getDataRaportare()))
            .satisfies(a -> assertThat(a.getSeveritate()).as("check severitate").isEqualTo(expected.getSeveritate()))
            .satisfies(a -> assertThat(a.getDescriere()).as("check descriere").isEqualTo(expected.getDescriere()))
            .satisfies(a -> assertThat(a.getEvolutie()).as("check evolutie").isEqualTo(expected.getEvolutie()))
            .satisfies(a -> assertThat(a.getRaportatDe()).as("check raportatDe").isEqualTo(expected.getRaportatDe()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReactieAdversaUpdatableRelationshipsEquals(ReactieAdversa expected, ReactieAdversa actual) {
        assertThat(actual)
            .as("Verify ReactieAdversa relationships")
            .satisfies(a -> assertThat(a.getMedicament()).as("check medicament").isEqualTo(expected.getMedicament()))
            .satisfies(a -> assertThat(a.getPacient()).as("check pacient").isEqualTo(expected.getPacient()));
    }
}
