package com.example.healthapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StudiiLiteraturaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudiiLiteraturaAllPropertiesEquals(StudiiLiteratura expected, StudiiLiteratura actual) {
        assertStudiiLiteraturaAutoGeneratedPropertiesEquals(expected, actual);
        assertStudiiLiteraturaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudiiLiteraturaAllUpdatablePropertiesEquals(StudiiLiteratura expected, StudiiLiteratura actual) {
        assertStudiiLiteraturaUpdatableFieldsEquals(expected, actual);
        assertStudiiLiteraturaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudiiLiteraturaAutoGeneratedPropertiesEquals(StudiiLiteratura expected, StudiiLiteratura actual) {
        assertThat(actual)
            .as("Verify StudiiLiteratura auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudiiLiteraturaUpdatableFieldsEquals(StudiiLiteratura expected, StudiiLiteratura actual) {
        assertThat(actual)
            .as("Verify StudiiLiteratura relevant properties")
            .satisfies(a -> assertThat(a.getTitlu()).as("check titlu").isEqualTo(expected.getTitlu()))
            .satisfies(a -> assertThat(a.getAutori()).as("check autori").isEqualTo(expected.getAutori()))
            .satisfies(a -> assertThat(a.getAnul()).as("check anul").isEqualTo(expected.getAnul()))
            .satisfies(a -> assertThat(a.getTipStudiu()).as("check tipStudiu").isEqualTo(expected.getTipStudiu()))
            .satisfies(a -> assertThat(a.getSubstanta()).as("check substanta").isEqualTo(expected.getSubstanta()))
            .satisfies(a -> assertThat(a.getConcluzie()).as("check concluzie").isEqualTo(expected.getConcluzie()))
            .satisfies(a -> assertThat(a.getLink()).as("check link").isEqualTo(expected.getLink()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudiiLiteraturaUpdatableRelationshipsEquals(StudiiLiteratura expected, StudiiLiteratura actual) {
        assertThat(actual)
            .as("Verify StudiiLiteratura relationships")
            .satisfies(a -> assertThat(a.getMedicament()).as("check medicament").isEqualTo(expected.getMedicament()));
    }
}
